psql -h pg -d studs << EOF

DROP VIEW FULL_OBSERVATION;
DROP TABLE OBSERVATION_EQUIPMENT;
DROP TABLE OBSERVATION CASCADE;
DROP TABLE EQUIPMENT;
DROP TABLE TYPE_EQUIPMENT;
DROP TYPE State_EQUIPMENT;
DROP TABLE OBJECT CASCADE;
EOF